### ISSUE TITLE
How to make images black and white?

### ISSUE THREAD

**Issue by MerlimarCode** [Jirka-Mayer/Mashcima#2]
Hello I was wondering how you managed to make the synthetic images black and white? I am currently trying to explore this repository but I can only mange to get the yellow and purple images displayed

**Comment by Jirka-Mayer** [comment]
That's due to matplotlib. The images are grayscale, so when you do:
```
plt.imshow(img)
```

it displays the 2D matrix as a heatmap. You can stack it, to make it RGB, then it's a 3D matrix with depth 3 and matplotlib interprets that as a colored image:
```
plt.imshow(np.dstack([img, img, img]))
```
